config/routes.rb
Faceshite::Application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users, shallow: true do
  	resources :missives
  end

  resources :relationships, only: [:index, :create, :destroy]

  controller :static_pages do
  	get 'contact' => :contact
  	get 'help' => :help
  	get 'about' => :about
  end

  root "static_pages#home"
end

app/models/missive.rb
# == Schema Information
#
# Table name: missives
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Missive < ActiveRecord::Base
	validates :title, :content, presence: true
	belongs_to :user
end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id              :integer          not null, primary key
#  user_id         :integer          not null
#  acquaintance_id :integer          not null
#  created_at      :datetime
#  updated_at      :datetime
#

class Relationship < ActiveRecord::Base
	belongs_to :user
	belongs_to :acquaintance, class_name: :User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  first_name      :string(255)
#  surname         :string(255)
#

class User < ActiveRecord::Base
	has_secure_password

	validates :email, :password_digest, :first_name, :surname, presence: true
	validates :password, length: { minimum: 6 }

	has_many :relationships
	has_many :acquaintances, through: :relationships

	has_many :inverse_relationships, class_name: "Relationship", 
																foreign_key: "acquaintance_id"
	has_many :inverse_acquaintances, through: :inverse_relationships, source: :user

	has_many :missives

 	def fullname
 		"#{first_name} #{surname}"
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 private

 	def current_user
 		@current_user ||= User.find(session[:user_id]) if session[:user_id]
 	end
 	helper_method :current_user

 	def authorize
 		redirect_to login_url, alert: "Not authorized!" if current_user.nil?
 	end
end

app/controllers/missives_controller.rb
class MissivesController < ApplicationController
	before_action :find_missive, only: [:show, :edit, :update, :destroy]
	before_action :authorize, only: [:edit, :update]

	def show
	end

	def index
		@missives = current_user.missives
	end

	def new
		@missive = current_user.missives.new
	end

	def create
		@missive = current_user.missives.new(missive_params)
		if @missive.save
			redirect_to current_user, notice: "Missive created!"
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @missive.update(missive_params)
			redirect_to @missive, notice: "Successfully updated!"
		else
			render "edit"
		end
	end

	def destroy
		@missive.destroy
		redirect_to user_missives_url(current_user), notice: "Missive deleted!"
	end

	private
		def missive_params
			params.require(:missive).permit(:title, :content)
		end

		def find_missive
			@missive = current_user.missives.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				redirect_to user_missives_url(current_user), alert: "Missive not found"
		end
end

app/controllers/relationship_controller.rb
class RelationshipController < ApplicationController
  def create
  	@relationship = current_user.relationships.build(acquaintance_id: params[:acquaintance_id])
  	if @relationship.save
  		redirect_to user_url(current_user), notice: "Friend added"
  	else
  		redirect_to root_url, notice: "Unable to add friend"
  	end
  end

  def destroy
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :find_relationships

	def index
	end

  def create
  	relationship = @relationships.build(acquaintance_id: params[:acquaintance_id])
  	if relationship.save
  		redirect_to user_url(current_user)
  	else
  		render "static_pages/home"
  	end
  end

  def destroy
  	relationship = @relationships.find(params[:id])
  	relationship.destroy
  	redirect_to users_url, notice: "Acquaintance removed"
  end

  private
  	def find_relationships
  		@relationships ||= current_user.relationships
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to user_url(user)
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
  end

  protected
  def user
    user = User.find_by email: (params[:email])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@user = User.new
  end

  def contact
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :edit, :update, :destroy]

	def show
		@acquaintances = @user.acquaintances
		@user.inverse_acquaintances.each { |user| @acquaintances << user }
	end

	def index
		@strangers = []
		strangers.each { |stranger| @strangers << stranger unless known?(stranger) }
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thank you for signing up!"
		else
			render 'static_pages/home'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user, notice: "User updated"
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to users_url, notice: "User destroyed!"
	end

	private
		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation,
																		:first_name, :surname)
		end

		def find_user
			@user = User.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				redirect_to users_url, alert: "User not found"
		end

		def greeting
			greetings = ["You again", "What's the point", "Why are you bothering"]
			greetings.sample
		end
		helper_method :greeting

		def strangers
			User.where.not(id: current_user)
		end

		def known?(user)
			current_user.acquaintances.include?(user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missives_helper.rb
module MissivesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= "Faceshite | #{yield(:title)}"
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
	%body
		%header
			#main_title faceshite
		%section
			#messages
				- flash.each do |key, value|
					.flash= value
			= yield
		%footer
			%p some footer text

app/views/missives/edit.html.haml
%h1 Edit
= form_for @missive do |f|
	- if @missive.errors.any?
		.error_explanation
			%h2= "#{pluralize(@missive.errors.count, "error")} prohibited this from being saved:"
			%ul
			- @missive.errors.full_messages.each do |msg|
				%li= msg
	%p	
		= f.label :title
		= f.text_field :title
	%p
		= f.label :content
		= f.text_area :content
	= f.submit

app/views/missives/index.html.haml
- @missives.each do |missive|
	= link_to missive.title, user_missive_path(current_user, missive)
	= missive.content
= link_to "Create a new missive", new_user_missive_path(current_user)

app/views/missives/new.html.haml
= form_for [current_user, @missive] do |f|
	- if @missive.errors.any?
		.error_explanation
			%h2= "#{pluralize(@missive.errors.count, "error")} prohibited this from being saved:"
			%ul
			- @missive.errors.full_messages.each do |msg|
				%li= msg
	%p	
		= f.label :title
		= f.text_field :title
	%p
		= f.label :content
		= f.text_area :content
	= f.submit

app/views/missives/show.html.haml
%h1= @missive.title
= @missive.content
= link_to 'edit', edit_missive_path(@missive)
= link_to 'delete', @missive, method: :delete, data: { confirm: "Are you sure" }

app/views/relationships/index.html.haml
= link_to "back", current_user
%h1 No more
- @relationships.each do |relationship|
	#possible_acquaintance
		= relationship.acquaintance.fullname
		= link_to "send a missive", new_user_missive_path(current_user)
		= link_to "delete acquaintance", relationship, method: :delete

app/views/static_pages/_login.html.haml
= form_tag session_path do
	.email.label= label_tag :email
	.email.field= text_field_tag :email, params[:email]
	.password.label= label_tag :password
	.password.field= password_field_tag :password
	#submit.field= submit_tag "Log In"

app/views/static_pages/_signup.html.haml
= form_for @user do |f|
	.signup= f.text_field :first_name, placeholder: "First Name", class: :signup_text
	.signup= f.text_field :surname, placeholder: "Surname", class: :signup_text
	.signup= f.email_field :email, placeholder: "Email", class: :signup_text
	.signup= f.password_field :password, placeholder: "Password", class: :signup_text
	.signup= f.password_field :password_confirmation, placeholder: "Confirm password", class: :signup_text
	.signup#signup_button= f.submit "Sign Up"

app/views/static_pages/about.html.haml
= provide(:title, "About")
%h1 StaticPages#about
%p Find me in app/views/static_pages/about.html.haml

app/views/static_pages/contact.html.haml
= provide(:title, "Contact Us")
%h1 StaticPages#contact
%p Find me in app/views/static_pages/contact.html.haml

app/views/static_pages/help.html.haml
= provide(:title, "Help")
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.haml

app/views/static_pages/home.html.haml
= provide(:title, "Home")
= render "static_pages/login"
#wrap
	#main
		%h2 Faceshite has no need for you!
		#welcome_image=image_tag 'GettyImages_78814284.jpg'
	#sidebar
		%h2 Sign up
		%h3 (if you must)
		- if @user
			- @user.errors.full_messages.each do |msg|
				= msg
		= render "static_pages/signup"

app/views/users/edit.html.haml
%h1 Edit User
= form_for @user do |f|
	- if @user.errors.any?
		.error_messages
			%h2 Form is invalid
			%ul
				- @user.errors.full_messages.each do |message|
					%li= message
	.field
		= f.label :first_name
		%br
		= f.text_field :first_name
	.field
		= f.label :surname
		%br
		= f.text_field :surname
	.field
		= f.label :email
		%br
		= f.email_field :email
	.field
		= f.label :password
		%br
		= f.password_field :password
	.field
		= f.label :password_confirmation
		%br
		= f.password_field :password_confirmation
	.actions= f.submit "Update user"

app/views/users/index.html.haml
%h1 Potential Acquaintances

- @strangers.each do |stranger|
	= link_to "#{stranger.fullname}", user_path(stranger)
	= link_to "Add as an acquaintance", relationships_path(acquaintance_id: stranger), method: :post

app/views/users/show.html.haml
= provide(:title, @user.first_name)
#user
	.greeting= "#{greeting} #{@user.first_name}?"
	.link= link_to "change your details", edit_user_path(@user)
	.link= link_to "log out", session_path(current_user), method: :delete
	.link= link_to "or leave forever!", user_path(@user), method: :delete

#acquaintances
	.link= link_to "you have #{pluralize(@acquaintances.count, 'acquaintance')}", relationships_path
	.link= link_to "find a new acquaintance", users_path

#missives
	%h2 Who loves you baby?
	- @user.missives.each do |missive|
		.missive= link_to missive.title, missive_path(missive)
		= missive.content